- .github/workflows/publish.yaml
Describe the changes introduced by this PR and what does it affect
> Adds workflow to run from zos-light

- bins/packages/mycelium/mycelium.sh
update mycelium to 0.5.4
update mycelium to 0.5.4
- #2398
> update mycelium to 0.5.4

- client/node.go
- docs/manual/api.md
- pkg/monitor.go
- pkg/monitord/system.go
- pkg/stubs/system_monitor_stub.go
- pkg/zos_api/routes.go
- pkg/zos_api/system.go
- pkg/zos_api/zos_api.go
add new endpoint to fetch node features
add new endpoint to fetch node features
- #2421
> add new endpoint to featch node features

- pkg/vm/ch.go
- pkg/vm/machine.go
fixes failure happens with some docker images
add `--xattr` to virtiofs
https://github.com/threefoldtech/zos/issues/2420
> fix failure to pull some docker images

- pkg/monitord/system.go
add mycelium and remove puplic ipv4 from node features
add mycelium and remove puplic ipv4 from node features
- https://github.com/threefoldtech/zos/issues/2434
> add mycelium and remove puplic ipv4 from node features

- .golangci.yml
- pkg/Makefile
- pkg/container/container.go
- pkg/container/stats/stats.go
- pkg/crypto/crypto_test.go
- pkg/flist/cleanup.go
- pkg/gridtypes/id.go
- pkg/gridtypes/workload_test.go
- pkg/gridtypes/zos/network_light.go
- pkg/netlight/ifaceutil/mac.go
- pkg/netlight/resource/mycelium.go
- pkg/perf/iperf/iperf_task.go
- pkg/perf/publicip/publicip_task.go
- pkg/power/ethtool.go
- pkg/primitives/vm-light/utils.go
- pkg/provision/auth.go
- pkg/provision/engine.go
- pkg/provision/storage.fs/storage.go
- pkg/storage/storage_test.go
- pkg/vm/manager.go
- pkg/zdb/admin.go
- tools/zos-update-worker/Makefile
- https://github.com/threefoldtech/zos/issues/2405
> fix linter

- pkg/environment/environment.go
- pkg/gridtypes/deployment.go
- pkg/provision/engine.go
only allow deployments of verified users
- #2444
> only allow deployments of verified users

- pkg/upgrade/upgrade.go
add current zos version to zos logs on upgrades
add current zos version to zos logs on upgrades
- #2418
> add current zos version to zos logs on upgrades

- docs/release/readme.md
update release docs to update chain version before creating release
update release docs to update chain version before creating release
- https://github.com/threefoldtech/zos/issues/2458
> update release docs to update chain version before creating release

- cmds/identityd/main.go
- cmds/modules/noded/main.go
- docs/release/readme.md
- pkg/Makefile
- pkg/api_gateway.go
- pkg/perf/cpubench/cpubench_task.go
- pkg/perf/healthcheck/healthcheck.go
- pkg/perf/healthcheck/ntp.go
- pkg/perf/monitor.go
- pkg/perf/publicip/publicip_task.go
- pkg/perf/zbusctx.go
- pkg/stubs/api_gateway_stub.go
- pkg/substrate_gateway/substrate_gateway.go
- pkg/upgrade/upgrade.go
- Sync changes from zos3
- changed the version in rollout json version to `version_light` to get the right zos4 version
> Development sync

- cmds/modules/gateway/main.go
- cmds/modules/netlightd/main.go
- cmds/zos/main.go
- docs/internals/boot.md
- etc/zinit/gateway.yaml
- etc/zinit/noded.yaml
- pkg/flist/flist.go
- pkg/gateway/flist.go
- pkg/gateway/gateway.go
- pkg/gateway/metrics.go
- pkg/gateway/metrics_test.go
- pkg/gateway/static.go
- pkg/gateway/static/cert.sh
- pkg/gateway/static/config.yaml
- pkg/gateway/static/dnsmasq.conf
- pkg/gridtypes/zos/types.go
- pkg/monitord/system.go
- pkg/netlight/network.go
- pkg/netlight/resource/mycelium.go
- pkg/netlight/resource/resource.go
- pkg/primitives/provisioner.go
Describe the changes introduced by this PR and what does it affect
> Adds gw and remove ndmz namespace

- cmds/modules/netlightd/main.go
- cmds/modules/noded/main.go
- cmds/modules/noded/public.go
- pkg/gateway/gateway.go
- pkg/monitord/system.go
- pkg/netlight/network.go
- pkg/network_light.go
- pkg/stubs/network_light_stub.go
- start redis consumer for the public config stream
- load domain from persist file instead of kernel
- https://github.com/threefoldtech/zos/issues/2525
> set public config in zoslight

- pkg/provision/engine.go
fix list_private_ips to include zoslight workloads
https://github.com/threefoldtech/zos/issues/2539
> fix list private ips to include zoslight workloads

- bins/packages/mycelium/mycelium.sh
> update mycelium to 0.6.1

- README.md
Update readme links
- https://github.com/threefoldtech/zos/issues/2548
> update docs urls in readme

- cmds/modules/netlightd/nft/rules.nft
> open email submission ports

- bins/packages/iperf/iperf.sh
> update iperf to latest

- cmds/modules/zui/header.go
clear registration error when node is registered
> clear registration error when node is registered

- cmds/modules/netlightd/main.go
- go.mod
- go.sum
Describe the changes introduced by this PR and what does it affect
> clean orphaned namespaces

- go.mod
- go.sum
Describe the changes introduced by this PR and what does it affect
> caching zos-config instead of getting it everytime from github
